--- !ruby/object:RDoc::RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:RDoc::Markup::Flow::P 
  body: Location of working config directory.
full_name: XDG#config_work
is_singleton: false
name: config_work
params: ()
visibility: public
