--- !ruby/object:RDoc::RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:RDoc::Markup::Flow::P 
  body: Access to configuration locations.
- !ruby/struct:RDoc::Markup::Flow::VERB 
  body: "  XDG.config.each{ |dir| ... }\n"
full_name: XDG#config
is_singleton: false
name: config
params: (*glob_and_flags, &block)
visibility: public
