--- !ruby/object:RDoc::RI::ModuleDescription 
attributes: []

class_methods: []

comment: 
- !ruby/struct:RDoc::Markup::Flow::H 
  level: 1
  text: CONFIGUTATION LOCATIONS
- !ruby/struct:RDoc::Markup::Flow::RULE 
  width: 
- !ruby/struct:RDoc::Markup::Flow::H 
  level: 1
  text: CONFIGUTATION LOCATIONS
constants: []

full_name: XDG::Config
includes: 
- !ruby/object:RDoc::RI::IncludedModule 
  name: Common
instance_methods: 
- !ruby/object:RDoc::RI::MethodSummary 
  name: dirs
- !ruby/object:RDoc::RI::MethodSummary 
  name: home
- !ruby/object:RDoc::RI::MethodSummary 
  name: work
name: Config
