--- !ruby/object:RDoc::RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:RDoc::Markup::Flow::P 
  body: Location of personal config directory.
full_name: XDG::Config#home
is_singleton: false
name: home
params: ()
visibility: public
